services:
  # MariaDB Database for Direct App Access
  mariadb:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword123
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=app_user
      - MARIADB_PASSWORD=apppassword123
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - moodle-network
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword123"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Our Moodle Integration App (Direct DB Access)
  moodle-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USE_DEMO_DATA=false
      - DEMO_MODE=false
      - DATABASE_URL=mysql://app_user:apppassword123@mariadb:3306/moodle
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=app_user
      - DB_PASSWORD=apppassword123
      - DB_NAME=moodle
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-direct_db_secret_key_change_for_production}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-pdf,doc,docx,txt,zip,jpg,png,jpeg,gif,ppt,pptx,xls,xlsx}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
      - app_uploads:/app/uploads
    networks:
      - moodle-network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # PhpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=app_user
      - PMA_PASSWORD=apppassword123
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - moodle-network
    restart: unless-stopped
    profiles:
      - admin

networks:
  moodle-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  app_logs:
    driver: local
  app_uploads:
    driver: local